name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
      - name: Build with Maven
        run: mvn -B package --file gamestudio_backend/pom.xml
        
      - name: Test with Maven
        run: mvn -B test surefire-report:report --file gamestudio_backend/pom.xml
        
      - name: list files
        run: ls gamestudio_backend/target/surefire-reports/TEST-*.xml
        
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: gamestudio_backend/target/site/jacoco/jacoco.xml
          
      - name: Comment coverage status on PR
        uses: codecov/comment-action@v2.0.0
        with:
          flags: all



