name: Java CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
      - name: Build with Maven
        run: mvn -B package --file gamestudio_backend/pom.xml
        
      - name: Test with Maven
        run: mvn -B test surefire-report:report --file gamestudio_backend/pom.xml
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: gamestudio_backend/target/surefire-reports

      - name: Test Report
        uses: mikeal/codecov-test-reporter@v0.1.4
        with:
          path: gamestudio_backend/target/surefire-reports
