name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
          
      - name: Build with Maven and Jacoco
        run: mvn -B clean verify org.jacoco:jacoco-maven-plugin:prepare-agent package --file gamestudio_backend/pom.xml
        
      - name: list files
        run: ls gamestudio_backend/target/site/jacoco/
        
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: gamestudio_backend/target/site/jacoco/jacoco.xml
