name: Java CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 19
    - name: Build with Maven
      run: mvn -B package --file gamestudio_backend/pom.xml
    - name: Test with Maven
      run: mvn -B package --file gamestudio_backend/pom.xml
