name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
          
      - name: Run controller tests
        run: mvn -B test -Dtest=sk.tuke.gamestudio_backend.controller.* --file gamestudio_backend/pom.xml

      - name: Run service tests
        run: mvn -B test -Dtest=sk.tuke.gamestudio_backend.service.* --file gamestudio_backend/pom.xml

      - name: list files
        run: ls gamestudio_backend/target/site/jacoco/
