name: Java CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
      - name: Build with Maven
        run: mvn -B package --file gamestudio_backend/pom.xml
        
      - name: Test with Maven
        run: mvn -B test surefire-report:report --file gamestudio_backend/pom.xml
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results.xml
          path: gamestudio_backend/target/surefire-reports
          
      - name: List test report files
        run: ls gamestudio_backend/target/surefire-reports
        
      - name: Test Report
        uses: dorny/test-reporter@v1
        with:
          artifact: '/test-results.*\.xml$/'
          name: 'Test Results'
          path: 'gamestudio_backend/target/surefire-reports'
          reporter: 'java-junit'
          only-summary: 'false'
          list-suites: 'all'
          list-tests: 'all'
          fail-on-error: 'true'
          token: ${{ github.token }}

