name: Java CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
      - name: Build with Maven
        run: mvn -B package --file gamestudio_backend/pom.xml
        
      - name: Test with Maven
        run: mvn -B test surefire-report:report --file gamestudio_backend/pom.xml
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: gamestudio_backend/target/surefire-reports
          
  test-report:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Test Results
        uses: actions/download-artifact@v2
        with:
          name: test-results
          path: test-results
      - name: Test Report
        uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: 'Test Results'
          path: '*.xml'
          reporter: 'java-junit'
          only-summary: 'false'
          list-suites: 'all'
          list-tests: 'all'
          fail-on-error: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}
